/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const TwarkuiIndexLazyImport = createFileRoute('/twarkui/')()
const ShadcnIndexLazyImport = createFileRoute('/shadcn/')()
const ShadcnChartsLazyImport = createFileRoute('/shadcn/charts')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TwarkuiIndexLazyRoute = TwarkuiIndexLazyImport.update({
  path: '/twarkui/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/twarkui/index.lazy').then((d) => d.Route))

const ShadcnIndexLazyRoute = ShadcnIndexLazyImport.update({
  path: '/shadcn/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/shadcn/index.lazy').then((d) => d.Route))

const ShadcnChartsLazyRoute = ShadcnChartsLazyImport.update({
  path: '/shadcn/charts',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/shadcn/charts.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/shadcn/charts': {
      id: '/shadcn/charts'
      path: '/shadcn/charts'
      fullPath: '/shadcn/charts'
      preLoaderRoute: typeof ShadcnChartsLazyImport
      parentRoute: typeof rootRoute
    }
    '/shadcn/': {
      id: '/shadcn/'
      path: '/shadcn'
      fullPath: '/shadcn'
      preLoaderRoute: typeof ShadcnIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/twarkui/': {
      id: '/twarkui/'
      path: '/twarkui'
      fullPath: '/twarkui'
      preLoaderRoute: typeof TwarkuiIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ShadcnChartsLazyRoute,
  ShadcnIndexLazyRoute,
  TwarkuiIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/shadcn/charts",
        "/shadcn/",
        "/twarkui/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/shadcn/charts": {
      "filePath": "shadcn/charts.lazy.tsx"
    },
    "/shadcn/": {
      "filePath": "shadcn/index.lazy.tsx"
    },
    "/twarkui/": {
      "filePath": "twarkui/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
